### PR TITLE
Add ios/android files

### PR DESCRIPTION
**Pull request by maartenhandels**
I ran the project locally and it generated this files. I checked with ChatGPT and it says these should be pushed in GitHub.

I'm wondering if this will cause issues on your side though since I imagine you already have a version of these files? @pprunty, maybe checkout this branch and see if you can still run everything on your machine

### CODE REVIEW

**Comment by pprunty** [comment]
> I ran the project locally and it generated this files. I checked with ChatGPT and it says these should be pushed in GitHub.
> 
> I'm wondering if this will cause issues on your side though since I imagine you already have a version of these files? @pprunty, maybe checkout this branch and see if you can still run everything on your machine

I have these files on my side. I think I only pushed up the `gradlew.bat` file though.

I know the `Podfile.lock` is generated when you run "pod install" from the iOS directory and is kind of like the `package-lock.json`. I generated this earlier today but removed it from my PR. I think this should be in the `.gitignore`.

Likewise, I think `gradlew.bat` is similar and should be in the `.gitignore`.

Not sure about the other Xcode file. Can probably put that in the .gitignore too. 

The `.gitignore` has lots of changes. Was this automatically generated? They all look good but covers lots of tools we are not including in our project, i.e "eclipse". But is a good base `.gitignore` for a react native project too :)

**Comment by pprunty** [comment]
> > I ran the project locally and it generated this files. I checked with ChatGPT and it says these should be pushed in GitHub.
> > I'm wondering if this will cause issues on your side though since I imagine you already have a version of these files? @pprunty, maybe checkout this branch and see if you can still run everything on your machine
> 
> I have these files on my side. I think I only pushed up the `gradlew.bat` file though.
> 
> I know the `Podfile.lock` is generated when you run "pod install" from the iOS directory and is kind of like the `package-lock.json`. I generated this earlier today but removed it from my PR. I think this should be in the `.gitignore`.
> 
> Likewise, I think `gradlew.bat` is similar and should be in the `.gitignore`.
> 
> Not sure about the other Xcode file. Can probably put that in the .gitignore too.
> 
> The `.gitignore` has lots of changes. Was this automatically generated? They all look good but covers lots of tools we are not including in our project, i.e "eclipse". But is a good base `.gitignore` for a react native project too :)

We should check with chatGPT on this too (can't wait for a chatGPT GitHub PR plugin)

**Comment by pprunty** [comment]
@maartenhandels missed your whatsappp message, will try run with your files tomorrow to check if they work. If they do, we can ignore my old messages about putting them in the .gitignore and get this PR merged

**Comment by maartenhandels** [comment]
> @maartenhandels missed your whatsappp message, will try run with your files tomorrow to check if they work. If they do, we can ignore my old messages about putting them in the .gitignore and get this PR merged

Sure! If you think they shouldn't be in GitHub you can do a little research on your side, but from what chatgpt was telling me those files are normally pushed

**Comment by pprunty** [comment]
> > @maartenhandels missed your whatsappp message, will try run with your files tomorrow to check if they work. If they do, we can ignore my old messages about putting them in the .gitignore and get this PR merged
> 
> Sure! If you think they shouldn't be in GitHub you can do a little research on your side, but from what chatgpt was telling me those files are normally pushed

happy to keep the files in the repository and will merge the branch :)

**Pull request merged**
